apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "athenz-issuer.name" . }}:leaderelection
  namespace: {{ .Release.namespace }}
  labels:
    app.kubernetes.io/component: "controller"
    {{- include "athenz-issuer.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "athenz-issuer.name" . }}:leaderelection
  namespace: {{ .Release.namespace }}
  labels:
    app.kubernetes.io/component: "controller"
    {{- include "athenz-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "athenz-issuer.name" . }}:leaderelection
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ template "athenz-issuer.serviceAccountName" . }}
  namespace: {{ .Release.namespace }}
