image:
  # The container registry to pull the controller image from.
  # +docs:property
  # registry: docker.io

  # The container image for the athenz-issuer controller.
  # +docs:property
  repository: docker.io/athenz/athenz-cert-manager-issuer

  # Override the image tag to deploy by setting this variable.
  # If no value is set, the chart's appVersion is used.
  # +docs:property
  # tag: vX.Y.Z

  # Target athenz-issuer digest. Override any tag, if set.
  # For example:
  #   manager: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
  # +docs:property=image.digest.manager
  # manager: sha256:...
  digest: {}

    
  # Kubernetes imagePullPolicy on Deployment
  pullPolicy: IfNotPresent

# Optional secrets used for pulling the athenz-issuer container image
# For example:
  #  imagePullSecrets:
  #    - name: "image-pull-secret"
imagePullSecrets: []

# Labels to apply to all resources
commonLabels: {}

# Override the full name
fullnameOverride:

# Override the name
nameOverride:

serviceAccount:
  # Specifies whether a service account should be created.
  create: true

  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  # +docs:property
  # name: ""

  # Optional additional annotations to add to the controller's Service Account.
  # +docs:property
  annotations: {}

  # Optional additional labels to add to the controller's Service Account.
  # +docs:property
  # labels: {}

  # Automount API credentials for a Service Account.
  automountServiceAccountToken: true

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

replicaCount: 1

crds:
  enabled: true
  keep: true
